#!/usr/bin/env python3
"""The hand, for the app's controls (brand book boards 05 and 06).

    python3 tools/build-hand.py

Writes a block of CSS custom properties between /*hand:start*/ and /*hand:end*/
in src/app.html. Each is a small SVG, as a data URL, used as a CSS mask: a
control paints its edge colour through it, so the colour stays in CSS
(--edge at rest, --acts under the cursor, --glaze when picked) and no control
carries any extra markup.

  --hand-w   a wide control's edge (menus, views, zoom), three frames side by
             side, drawn at 150 x 40 so the stretch to a real key stays small
  --hand-wf  the same three shapes, filled, for a picked (glazed) key
  --hand-s   a square control's edge (the Style panel's options), 40 x 40
  --hand-sf  the same, filled
  --hand-c   a card in the key list (1.12.0), 320 x 170, three frames
  --hand-k   a keycap (kbd), one frame, outline
  --hand-kf  the same keycap, filled

The drawing is board 05's: amplitude 1.2, sampled every 10 to 13px, round
joins, a second pass at 62 percent and half opacity. Strokes are
non-scaling so a stretched mask keeps a 1.5px line. Seeds are fixed, so the
output is the same every run and the diff only moves when this file does.
"""
import math, pathlib, random, re, urllib.parse

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "app.html"
AMP, LO, HI = 1.2, 10.0, 13.0


def resample(poly, rnd):
    out, carry, target = [poly[0]], 0.0, rnd.uniform(LO, HI)
    for a, b in zip(poly, poly[1:]):
        L = math.hypot(b[0] - a[0], b[1] - a[1]) or 1e-9
        t = 0.0
        while carry + (L - t) >= target:
            t += target - carry
            out.append((a[0] + (b[0] - a[0]) * t / L, a[1] + (b[1] - a[1]) * t / L))
            carry, target = 0.0, rnd.uniform(LO, HI)
        carry += L - t
    return out


def edge(w, h, seed, inset, amp=AMP, dx=0):
    rnd = random.Random(seed)
    r = min(5.0, h / 5)
    box = []
    for cx, cy, a0 in ((w - inset - r, inset + r, -90), (w - inset - r, h - inset - r, 0),
                       (inset + r, h - inset - r, 90), (inset + r, inset + r, 180)):
        for k in range(4):
            a = math.radians(a0 + k * 30)
            box.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    box.append(box[0])
    p = [(x + rnd.uniform(-amp, amp), y + rnd.uniform(-amp, amp)) for x, y in resample(box, rnd)]
    p[-1] = p[0]
    return 'M' + ' L'.join(f'{x + dx:.1f} {y:.1f}' for x, y in p) + ' Z'


def sprite(w, h, seed, frames, filled, sw=1.5):
    parts = []
    for f in range(frames):
        dx = f * w
        a = edge(w, h, seed * 10 + f, 2.2, dx=dx)
        b = edge(w, h, seed * 10 + f + 5, 2.6, dx=dx)
        if filled:
            parts.append(f'<path d="{a}" fill="#000"/>')
        else:
            parts.append(f'<path d="{a}" fill="none" stroke="#000" stroke-width="{sw}" vector-effect="non-scaling-stroke" stroke-linejoin="round"/>'
                         f'<path d="{b}" fill="none" stroke="#000" stroke-width="{sw * .62:.2f}" vector-effect="non-scaling-stroke" stroke-linejoin="round" opacity=".5"/>')
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w * frames} {h}" preserveAspectRatio="none">'
           + ''.join(parts) + '</svg>')
    return 'url("data:image/svg+xml,' + urllib.parse.quote(svg, safe=' /=:,.-"') .replace('"', "'") + '")'


def main():
    props = {
        '--hand-w': sprite(150, 40, 71, 3, False),
        '--hand-wf': sprite(150, 40, 71, 3, True),
        '--hand-s': sprite(40, 40, 33, 3, False),
        '--hand-sf': sprite(40, 40, 33, 3, True),
        '--hand-c': sprite(320, 170, 91, 3, False, 1.4),
        '--hand-k': sprite(30, 24, 51, 1, False, 1.3),
        '--hand-kf': sprite(30, 24, 51, 1, True),
    }
    block = ('/*hand:start*/\n  /* Generated by tools/build-hand.py. Do not hand-edit. */\n  :root{\n'
             + ''.join(f'    {k}:{v};\n' for k, v in props.items()) + '  }\n  /*hand:end*/')
    s = SRC.read_text()
    if '/*hand:start*/' not in s:
        sys.exit('no /*hand:start*/ marker in src/app.html')
    s = re.sub(r'/\*hand:start\*/.*?/\*hand:end\*/', lambda m: block, s, flags=re.S)
    SRC.write_text(s)
    print(f'hand: {len(block)} bytes of masks')


if __name__ == '__main__':
    import sys
    main()
